### ISSUE TITLE
Milestone 4 - App improvements

### ISSUE THREAD

**Issue by nobbynguyen** [UBC-MDS/netviz#47]
At least five improvements: 
1. Styling: 
- Recolour plot headers for readability, 
- Make plot sizes same for ratings and Netflix movies over time
- Reduce size of table and increase size for world map since world map looks shrunken;	
- Add a year column to the table, then sort by descending order. (probably a note of the order)
2. Comments from the peer review: documentation
- Rename world map title with short description
- Add more explanation for movie rating plot in description README;
- Styling for table of examples for readability;		
3. TA feedback (do we have any?)

**Comment by nobbynguyen** [comment]
You should paste the link to the commits in the submission with a brief description of the change (similar to a meaningful commit message).

**Comment by y248guo** [comment]
# App improvements

> Blockquotes are the comments from the peer review
> Link to peer review is [here](https://github.com/UBC-MDS/DSCI532-peer-review/issues/7)

Improvements based on the reviews:
1.  Recolour plot headers for readability,
	> The header colour for “World Map” appears to be a lighter shade than the other headers and is harder to read with the yellow font. A darker shade might help increase contrast and readability.
	- The colour schemes of header cards have been changed to the Netflix colour scheme with black dark fill-in colour and red font colour
	- [Commit link](https://github.com/UBC-MDS/netviz/pull/50/commits/abbaa7d3c0a891242bbaa8056173afd05ceb6af7)
2.  Make plot sizes the same for ratings and Netflix movies over time
	> The plot of `Ratings` and `Netflix Movies over Time` are of different plot sizes which keep changing based on the genre selected. It would be great if you could make both the plot sizes the same.
	- Plots now have fixed scales, but since the scales are fixed, now there will be values going over the fixed scale since the number of movies per genre varies a lot
	- [Commit link](https://github.com/UBC-MDS/netviz/pull/50/commits/1c555a045e247830dcaf1905869990d1d6f870c7)
3.  Reduce the size of the table and increase the size of the world map since the world map looks shrunken;
	> The world map plot is an interesting plot. It would be great if you could provide interactivity to it. Also, the plot looks shrunken, the table plot can be reduced in size to increase the visual representation of the world map.
	- I am not sure what proper interactivity can be added, but the arrangement of the plots are now changed, such that the world map plot would be larger
		- The suggested sliding bar for the year would not be appropriate here, since the data would be grouped for counting, year data would not be easily available (even though it is doable, it requires way too much time given the current deadline); plus the time plot is given for some ideas of the global changes over time
	- A title also has been added to improve communication of what this world map is showing, regarding this comment:
	> For example, in the plot named “World map”, I found it hard to understand what the app was showing. It could mean how many users in different countries were using Netflix as well without providing sufficient context information.
	- [Commit link](https://github.com/UBC-MDS/netviz/pull/50/commits/e7f162d6099f046bb07b21773cbe2d9ebddcfd38)
4.  Add a year column to the table, then sort by descending order. (probably a note of the order)
	> Table of Examples can incorporate other information like film’s year so that stakeholders can get more insight on these films and perhaps be ordered in descending order of the year. 
	- The year of release and the duration of the movie are now added to the table, and the results are ordered in descending order of the release year
	- [Commit link](https://github.com/UBC-MDS/netviz/pull/50/commits/3443fc09c16e9e366318b2f03c9677881d5df92f)
5. Rename the world map title with a short description
	- Change the Card label to a short description instead of "World Map"
	- This has been handled by the previous commit
6. Add more explanation for movie rating plot in description README;
	> However, it would be better if more explanation could be provided about the movie rating. This part is not that intuitive.
	- Extra explanation and clarification have been added for the movie rating plot
	- [Commit link](https://github.com/UBC-MDS/netviz/pull/50/commits/32506920664a6fb0515849d1df6f9d5815d61a7b)
	- The name of the rating plot has also been changed to avoid confusion with the actual rating of the movie (here the data we have is the maturity rating)
		- This was added in a separate commit ([commit link](https://github.com/UBC-MDS/netviz/pull/50/commits/569653e7c85e5c60d20fe5e546f3a29a1bd688f1))
7. Styling for a table of examples for readability;
	> Styling could be added to the Table of Examples to help increase readability, such as a bolded header, striped rows, and left alignment for text columns.
	- The improved styles have been added for the table (now changed the name to Table of Netflix Movies for the more meaningful title)
	- Also added a sorting option for the columns
	- [Commit link](https://github.com/UBC-MDS/netviz/pull/50/commits/968cf5e42c91df35bdbc8b391356962f0a256bee)
